// <auto-generated />
using System;
using Comunidad.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Comunidad.Infraestructura.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190614000414_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Acreditacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EstaBorrado");

                    b.Property<long?>("EventoId");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("Date");

                    b.Property<long>("PersonaId");

                    b.Property<long>("ProgramacionId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("ProgramacionId");

                    b.ToTable("Acreditaciones");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Entrada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadDisponible");

                    b.Property<bool>("EstaBorrado");

                    b.Property<long>("EventoId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("TipoEntrada");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000);

                    b.Property<bool>("EsPaginaPublica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EstaBorrado");

                    b.Property<string>("FileName")
                        .HasMaxLength(150);

                    b.Property<bool>("MostrarLasEntradasRestantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<string>("Organizador")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Path")
                        .HasMaxLength(400);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("TemaEventoId");

                    b.Property<long>("TipoEventoId");

                    b.Property<long?>("UbicacionId");

                    b.HasKey("Id");

                    b.HasIndex("TemaEventoId");

                    b.HasIndex("TipoEventoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Inscripcion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("EntradaId");

                    b.Property<bool>("EstaBorrado");

                    b.Property<int>("EstadoInscripcion");

                    b.Property<long?>("EventoId");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("DateTime");

                    b.Property<long?>("OcupacionId");

                    b.Property<long>("PersonaId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("EntradaId");

                    b.HasIndex("EventoId");

                    b.HasIndex("OcupacionId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Ocupacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<bool>("EstaBorrado");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Ocupaciones");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Pais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("EstaBorrado");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descripcion = "AFGANISTÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 2L,
                            Descripcion = "ALBANIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 3L,
                            Descripcion = "ALEMANIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 4L,
                            Descripcion = "ANDORRA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 5L,
                            Descripcion = "ANGOLA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 6L,
                            Descripcion = "ANTIGUA Y BARBUDA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 7L,
                            Descripcion = "ARABIA SAUDITA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 8L,
                            Descripcion = "ARGELIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 9L,
                            Descripcion = "ARGENTINA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 10L,
                            Descripcion = "ARMENIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 11L,
                            Descripcion = "AUSTRALIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 12L,
                            Descripcion = "AUSTRIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 13L,
                            Descripcion = "AZERBAIYÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 14L,
                            Descripcion = "BAHAMAS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 15L,
                            Descripcion = "BANGLADÉS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 16L,
                            Descripcion = "BARBADOS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 17L,
                            Descripcion = "BARÉIN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 18L,
                            Descripcion = "BÉLGICA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 19L,
                            Descripcion = "BELICE",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 20L,
                            Descripcion = "BENÍN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 21L,
                            Descripcion = "BIELORRUSIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 22L,
                            Descripcion = "BIRMANIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 23L,
                            Descripcion = "BOLIVIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 24L,
                            Descripcion = "BOSNIA Y HERZEGOVINA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 25L,
                            Descripcion = "BOTSUANA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 26L,
                            Descripcion = "BRASIL",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 27L,
                            Descripcion = "BRUNÉI",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 28L,
                            Descripcion = "BULGARIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 29L,
                            Descripcion = "BURKINA FASO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 30L,
                            Descripcion = "BURUNDI",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 31L,
                            Descripcion = "BUTÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 32L,
                            Descripcion = "CABO VERDE",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 33L,
                            Descripcion = "CAMBOYA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 34L,
                            Descripcion = "CAMERÚN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 35L,
                            Descripcion = "CANADÁ",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 36L,
                            Descripcion = "CATAR",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 37L,
                            Descripcion = "CHAD",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 38L,
                            Descripcion = "CHILE",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 39L,
                            Descripcion = "CHINA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 40L,
                            Descripcion = "CHIPRE",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 41L,
                            Descripcion = "CIUDAD DEL VATICANO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 42L,
                            Descripcion = "COLOMBIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 43L,
                            Descripcion = "COMORAS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 44L,
                            Descripcion = "COREA DEL NORTE",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 45L,
                            Descripcion = "COREA DEL SUR",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 46L,
                            Descripcion = "COSTA DE MARFIL",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 47L,
                            Descripcion = "COSTA RICA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 48L,
                            Descripcion = "CROACIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 49L,
                            Descripcion = "CUBA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 50L,
                            Descripcion = "DINAMARCA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 51L,
                            Descripcion = "DOMINICA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 52L,
                            Descripcion = "ECUADOR",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 53L,
                            Descripcion = "EGIPTO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 54L,
                            Descripcion = "EL SALVADOR",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 55L,
                            Descripcion = "EMIRATOS ÁRABES UNIDOS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 56L,
                            Descripcion = "ERITREA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 57L,
                            Descripcion = "ESLOVAQUIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 58L,
                            Descripcion = "ESLOVENIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 59L,
                            Descripcion = "ESPAÑA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 60L,
                            Descripcion = "ESTADOS UNIDOS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 61L,
                            Descripcion = "ESTONIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 62L,
                            Descripcion = "ETIOPÍA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 63L,
                            Descripcion = "FILIPINAS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 64L,
                            Descripcion = "FINLANDIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 65L,
                            Descripcion = "FIYI",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 66L,
                            Descripcion = "FRANCIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 67L,
                            Descripcion = "GABÓN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 68L,
                            Descripcion = "GAMBIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 69L,
                            Descripcion = "GEORGIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 70L,
                            Descripcion = "GHANA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 71L,
                            Descripcion = "GRANADA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 72L,
                            Descripcion = "GRECIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 73L,
                            Descripcion = "GUATEMALA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 74L,
                            Descripcion = "GUYANA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 75L,
                            Descripcion = "GUINEA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 76L,
                            Descripcion = "GUINEA ECUATORIAL",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 77L,
                            Descripcion = "GUINEA-BISÁU",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 78L,
                            Descripcion = "HAITÍ",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 79L,
                            Descripcion = "HONDURAS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 80L,
                            Descripcion = "HUNGRÍA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 81L,
                            Descripcion = "INDIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 82L,
                            Descripcion = "INDONESIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 83L,
                            Descripcion = "IRAK",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 84L,
                            Descripcion = "IRÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 85L,
                            Descripcion = "IRLANDA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 86L,
                            Descripcion = "ISRAEL",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 87L,
                            Descripcion = "ISLANDIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 88L,
                            Descripcion = "ISLAS MARSHALL",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 89L,
                            Descripcion = "ISLAS SALOMÓN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 90L,
                            Descripcion = "ISRAEL",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 91L,
                            Descripcion = "ITALIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 92L,
                            Descripcion = "JAMAICA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 93L,
                            Descripcion = "JAPÓN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 94L,
                            Descripcion = "JORDANIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 95L,
                            Descripcion = "KAZAJISTÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 96L,
                            Descripcion = "KENIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 97L,
                            Descripcion = "KIRGUISTÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 98L,
                            Descripcion = "KIRIBATI",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 99L,
                            Descripcion = "KUWAIT",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 100L,
                            Descripcion = "LAOS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 101L,
                            Descripcion = "LESOTO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 102L,
                            Descripcion = "LETONIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 103L,
                            Descripcion = "LÍBANO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 104L,
                            Descripcion = "LIBERIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 105L,
                            Descripcion = "LIBIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 106L,
                            Descripcion = "LIECHTENSTEIN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 107L,
                            Descripcion = "LITUANIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 108L,
                            Descripcion = "LUXEMBURGO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 109L,
                            Descripcion = "MADAGASCAR",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 110L,
                            Descripcion = "MALASIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 111L,
                            Descripcion = "MALAUI",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 112L,
                            Descripcion = "MALDIVAS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 113L,
                            Descripcion = "MALÍ",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 114L,
                            Descripcion = "MALTA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 115L,
                            Descripcion = "MARRUECOS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 116L,
                            Descripcion = "MAURICIO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 117L,
                            Descripcion = "MAURITANIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 118L,
                            Descripcion = "MÉXICO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 119L,
                            Descripcion = "MICRONESIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 120L,
                            Descripcion = "MOLDAVIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 121L,
                            Descripcion = "MÓNACO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 122L,
                            Descripcion = "MONGOLIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 123L,
                            Descripcion = "MONTENEGRO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 124L,
                            Descripcion = "MOZAMBIQUE",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 125L,
                            Descripcion = "NAMIBIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 126L,
                            Descripcion = "NAURU",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 127L,
                            Descripcion = "NEPAL",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 128L,
                            Descripcion = "NICARAGUA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 129L,
                            Descripcion = "NÍGER",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 130L,
                            Descripcion = "NIGERIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 131L,
                            Descripcion = "NORUEGA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 132L,
                            Descripcion = "NUEVA ZELANDA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 133L,
                            Descripcion = "OMÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 134L,
                            Descripcion = "PAÍSES BAJOS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 135L,
                            Descripcion = "PAKISTÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 136L,
                            Descripcion = "PALAOS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 137L,
                            Descripcion = "PANAMÁ",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 138L,
                            Descripcion = "PAPÚA NUEVA GUINEA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 139L,
                            Descripcion = "PARAGUAY",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 140L,
                            Descripcion = "PERÚ",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 141L,
                            Descripcion = "POLONIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 142L,
                            Descripcion = "PORTUGAL",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 143L,
                            Descripcion = "REINO UNIDO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 144L,
                            Descripcion = "REPÚBLICA CENTROAFRICANA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 145L,
                            Descripcion = "REPÚBLICA CHECA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 146L,
                            Descripcion = "REPÚBLICA DE MACEDONIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 147L,
                            Descripcion = "REPÚBLICA DEL CONGO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 148L,
                            Descripcion = "REPÚBLICA DEMOCRÁTICA DEL CONGO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 149L,
                            Descripcion = "REPÚBLICA DOMINICANA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 150L,
                            Descripcion = "REPÚBLICA SUDAFRICANA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 151L,
                            Descripcion = "RUANDA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 152L,
                            Descripcion = "RUMANÍA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 153L,
                            Descripcion = "RUSIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 154L,
                            Descripcion = "SAMOA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 155L,
                            Descripcion = "SAN CRISTÓBAL Y NIEVES",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 156L,
                            Descripcion = "SAN MARINO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 157L,
                            Descripcion = "SAN VICENTE Y LAS GRANADINAS",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 158L,
                            Descripcion = "SANTA LUCÍA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 159L,
                            Descripcion = "SANTO TOMÉ Y PRÍNCIPE",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 160L,
                            Descripcion = "SENEGAL",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 161L,
                            Descripcion = "SERBIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 162L,
                            Descripcion = "SEYCHELLES",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 163L,
                            Descripcion = "SIERRA LEONA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 164L,
                            Descripcion = "SINGAPUR",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 165L,
                            Descripcion = "SIRIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 166L,
                            Descripcion = "SOMALIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 167L,
                            Descripcion = "SRI LANKA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 168L,
                            Descripcion = "SUAZILANDIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 169L,
                            Descripcion = "SUDÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 170L,
                            Descripcion = "SUDÁN DEL SUR",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 171L,
                            Descripcion = "SUECIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 172L,
                            Descripcion = "SUIZA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 173L,
                            Descripcion = "SURINAM",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 174L,
                            Descripcion = "TAILANDIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 175L,
                            Descripcion = "TANZANIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 176L,
                            Descripcion = "TAYIKISTÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 177L,
                            Descripcion = "TIMOR ORIENTAL",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 178L,
                            Descripcion = "TOGO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 179L,
                            Descripcion = "TONGA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 180L,
                            Descripcion = "TRINIDAD Y TOBAGO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 181L,
                            Descripcion = "TÚNEZ",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 182L,
                            Descripcion = "TURKMENISTÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 183L,
                            Descripcion = "TURQUÍA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 184L,
                            Descripcion = "TUVALU",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 185L,
                            Descripcion = "UCRANIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 186L,
                            Descripcion = "UGANDA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 187L,
                            Descripcion = "URUGUAY",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 188L,
                            Descripcion = "UZBEKISTÁN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 189L,
                            Descripcion = "VANUATU",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 190L,
                            Descripcion = "VENEZUELA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 191L,
                            Descripcion = "VIETNAM",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 192L,
                            Descripcion = "YEMEN",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 193L,
                            Descripcion = "YIBUTI",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 194L,
                            Descripcion = "ZAMBIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 195L,
                            Descripcion = "ZIMBABUE",
                            EstaBorrado = false
                        });
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AltaPorMostrador");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("ApellidoCasada")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Celular")
                        .HasMaxLength(25);

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("Email")
                        .HasMaxLength(250);

                    b.Property<bool>("EstaBorrado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Telefono")
                        .HasMaxLength(25);

                    b.Property<long?>("UbicacionId");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Programacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EstaBorrado");

                    b.Property<long>("EventoId");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("Date");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("Date");

                    b.Property<string>("HoraEntrada")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("HoraSalida")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Programaciones");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.TemaEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<bool>("EstaBorrado");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("TemaEventos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descripcion = "CONCIERTO O PERFORMANCE",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 2L,
                            Descripcion = "CAMPAMENTO O RETIRO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 3L,
                            Descripcion = "CARRERA O EVENTO DEPORTIVO",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 4L,
                            Descripcion = "CONFERENCIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 5L,
                            Descripcion = "CONVENCION",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 6L,
                            Descripcion = "FESTIVAL O FERIA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 7L,
                            Descripcion = "FIESTA O REUNION SOCIAL",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 8L,
                            Descripcion = "TV SHOW",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 9L,
                            Descripcion = "SEMINARIO O CHARLA",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 10L,
                            Descripcion = "OTROS",
                            EstaBorrado = false
                        });
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.TipoEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<bool>("EstaBorrado");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("TipoEventos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descripcion = "Hogar y estilo de vida",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 2L,
                            Descripcion = "Artes escenicas y visuales",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 3L,
                            Descripcion = "Cine medios de comunicacion y entretenimiento",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 4L,
                            Descripcion = "Deportes y salud",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 5L,
                            Descripcion = "Dias de fiesta",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 6L,
                            Descripcion = "Familias y educacion",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 7L,
                            Descripcion = "Gastronomia",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 8L,
                            Descripcion = "Política",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 9L,
                            Descripcion = "Moda y belleza ",
                            EstaBorrado = false
                        },
                        new
                        {
                            Id = 10L,
                            Descripcion = "Otros",
                            EstaBorrado = false
                        });
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Ubicacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciudad")
                        .HasMaxLength(250);

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<long?>("PaisId");

                    b.Property<string>("Provincia")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Ubicacion");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EstaBorrado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("PersonaId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Acreditacion", b =>
                {
                    b.HasOne("Comunidad.Dominio.Entidades.Evento")
                        .WithMany("Acreditaciones")
                        .HasForeignKey("EventoId");

                    b.HasOne("Comunidad.Dominio.Entidades.Persona", "Persona")
                        .WithMany("Acreditaciones")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_Persona_Acreditaciones")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Comunidad.Dominio.Entidades.Programacion", "Programacion")
                        .WithMany("Acreditaciones")
                        .HasForeignKey("ProgramacionId")
                        .HasConstraintName("FK_Programacion_Acreditaciones")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Entrada", b =>
                {
                    b.HasOne("Comunidad.Dominio.Entidades.Evento", "Evento")
                        .WithMany("Entradas")
                        .HasForeignKey("EventoId")
                        .HasConstraintName("FK_Entrada_Evento")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Evento", b =>
                {
                    b.HasOne("Comunidad.Dominio.Entidades.TemaEvento", "TemaEvento")
                        .WithMany("Eventos")
                        .HasForeignKey("TemaEventoId")
                        .HasConstraintName("FK_TemaEvento_Eventos")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Comunidad.Dominio.Entidades.TipoEvento", "TipoEvento")
                        .WithMany("Eventos")
                        .HasForeignKey("TipoEventoId")
                        .HasConstraintName("FK_TipoEvento_Eventos")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Comunidad.Dominio.Entidades.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Inscripcion", b =>
                {
                    b.HasOne("Comunidad.Dominio.Entidades.Entrada", "Entrada")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EntradaId")
                        .HasConstraintName("FK_Inscripcion_Entrada")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Comunidad.Dominio.Entidades.Evento")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EventoId");

                    b.HasOne("Comunidad.Dominio.Entidades.Ocupacion", "Ocupacion")
                        .WithMany("Inscripciones")
                        .HasForeignKey("OcupacionId");

                    b.HasOne("Comunidad.Dominio.Entidades.Persona", "Persona")
                        .WithMany("Inscripciones")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_Persona_Inscripciones")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Persona", b =>
                {
                    b.HasOne("Comunidad.Dominio.Entidades.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Programacion", b =>
                {
                    b.HasOne("Comunidad.Dominio.Entidades.Evento", "Evento")
                        .WithMany("Programaciones")
                        .HasForeignKey("EventoId")
                        .HasConstraintName("FK_Programacion_Evento")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Ubicacion", b =>
                {
                    b.HasOne("Comunidad.Dominio.Entidades.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId");
                });

            modelBuilder.Entity("Comunidad.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("Comunidad.Dominio.Entidades.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("Comunidad.Dominio.Entidades.Usuario", "PersonaId")
                        .HasConstraintName("FK_Usuario_Persona")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
