namespace Comunidad.Dominio.MetaData
{
    using Comunidad.Dominio.Entidades;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using System.Collections.Generic;

    public class PaisMetaData : IEntityTypeConfiguration<Pais>
    {
        public void Configure(EntityTypeBuilder<Pais> builder)
        {
            builder.Property(x => x.Descripcion)
                .HasMaxLength(100)
                .HasField("_descripcion")
                .IsRequired();

            builder.HasQueryFilter(x => x.EstaBorrado == false);

            builder.HasData(Seed());
        }

        private List<Pais> Seed()
        {
            var listaPaises = new List<Pais>
            {
                new Pais {Id = 1, Descripcion = "Afganistán" },
                new Pais {Id = 2, Descripcion = "Albania" },
                new Pais {Id = 3, Descripcion = "Alemania" },
                new Pais {Id = 4, Descripcion = "Andorra" },
                new Pais {Id = 5, Descripcion = "Angola" },
                new Pais {Id = 6, Descripcion = "Antigua y Barbuda" },
                new Pais {Id = 7, Descripcion = "Arabia Saudita" },
                new Pais {Id = 8, Descripcion = "Argelia" },
                new Pais {Id = 9, Descripcion = "Argentina" },
                new Pais {Id = 10, Descripcion = "Armenia" },
                new Pais {Id = 11, Descripcion = "Australia" },
                new Pais {Id = 12, Descripcion = "Austria" },
                new Pais {Id = 13, Descripcion = "Azerbaiyán" },
                new Pais {Id = 14, Descripcion = "Bahamas" },
                new Pais {Id = 15, Descripcion = "Bangladés" },
                new Pais {Id = 16, Descripcion = "Barbados" },
                new Pais {Id = 17, Descripcion = "Baréin" },
                new Pais {Id = 18, Descripcion = "Bélgica" },
                new Pais {Id = 19, Descripcion = "Belice" },
                new Pais {Id = 20, Descripcion = "Benín" },
                new Pais {Id = 21, Descripcion = "Bielorrusia" },
                new Pais {Id = 22, Descripcion = "Birmania" },
                new Pais {Id = 23, Descripcion = "Bolivia" },
                new Pais {Id = 24, Descripcion = "Bosnia y Herzegovina" },
                new Pais {Id = 25, Descripcion = "Botsuana" },
                new Pais {Id = 26, Descripcion = "Brasil" },
                new Pais {Id = 27, Descripcion = "Brunéi" },
                new Pais {Id = 28, Descripcion = "Bulgaria" },
                new Pais {Id = 29, Descripcion = "Burkina Faso" },
                new Pais {Id = 30, Descripcion = "Burundi" },
                new Pais {Id = 31, Descripcion = "Bután" },
                new Pais {Id = 32, Descripcion = "Cabo Verde" },
                new Pais {Id = 33, Descripcion = "Camboya" },
                new Pais {Id = 34, Descripcion = "Camerún" },
                new Pais {Id = 35, Descripcion = "Canadá" },
                new Pais {Id = 36, Descripcion = "Catar" },
                new Pais {Id = 37, Descripcion = "Chad" },
                new Pais {Id = 38, Descripcion = "Chile" },
                new Pais {Id = 39, Descripcion = "China" },
                new Pais {Id = 40, Descripcion = "Chipre" },
                new Pais {Id = 41, Descripcion = "Ciudad del Vaticano" },
                new Pais {Id = 42, Descripcion = "Colombia" },
                new Pais {Id = 43, Descripcion = "Comoras" },
                new Pais {Id = 44, Descripcion = "Corea del Norte" },
                new Pais {Id = 45, Descripcion = "Corea del Sur" },
                new Pais {Id = 46, Descripcion = "Costa de Marfil" },
                new Pais {Id = 47, Descripcion = "Costa Rica" },
                new Pais {Id = 48, Descripcion = "Croacia" },
                new Pais {Id = 49, Descripcion = "Cuba" },
                new Pais {Id = 50, Descripcion = "Dinamarca" },
                new Pais {Id = 51, Descripcion = "Dominica" },
                new Pais {Id = 52, Descripcion = "Ecuador" },
                new Pais {Id = 53, Descripcion = "Egipto" },
                new Pais {Id = 54, Descripcion = "El Salvador" },
                new Pais {Id = 55, Descripcion = "Emiratos Árabes Unidos" },
                new Pais {Id = 56, Descripcion = "Eritrea" },
                new Pais {Id = 57, Descripcion = "Eslovaquia" },
                new Pais {Id = 58, Descripcion = "Eslovenia" },
                new Pais {Id = 59, Descripcion = "España" },
                new Pais {Id = 60, Descripcion = "Estados Unidos" },
                new Pais {Id = 61, Descripcion = "Estonia" },
                new Pais {Id = 62, Descripcion = "Etiopía" },
                new Pais {Id = 63, Descripcion = "Filipinas" },
                new Pais {Id = 64, Descripcion = "Finlandia" },
                new Pais {Id = 65, Descripcion = "Fiyi" },
                new Pais {Id = 66, Descripcion = "Francia" },
                new Pais {Id = 67, Descripcion = "Gabón" },
                new Pais {Id = 68, Descripcion = "Gambia" },
                new Pais {Id = 69, Descripcion = "Georgia" },
                new Pais {Id = 70, Descripcion = "Ghana" },
                new Pais {Id = 71, Descripcion = "Granada" },
                new Pais {Id = 72, Descripcion = "Grecia" },
                new Pais {Id = 73, Descripcion = "Guatemala" },
                new Pais {Id = 74, Descripcion = "Guyana" },
                new Pais {Id = 75, Descripcion = "Guinea" },
                new Pais {Id = 76, Descripcion = "Guinea ecuatorial" },
                new Pais {Id = 77, Descripcion = "Guinea-Bisáu" },
                new Pais {Id = 78, Descripcion = "Haití" },
                new Pais {Id = 79, Descripcion = "Honduras" },
                new Pais {Id = 80, Descripcion = "Hungría" },
                new Pais {Id = 81, Descripcion = "India" },
                new Pais {Id = 82, Descripcion = "Indonesia" },
                new Pais {Id = 83, Descripcion = "Irak" },
                new Pais {Id = 84, Descripcion = "Irán" },
                new Pais {Id = 85, Descripcion = "Irlanda" },
                new Pais {Id = 86, Descripcion = "Israel" },
                new Pais {Id = 87, Descripcion = "Islandia" },
                new Pais {Id = 88, Descripcion = "Islas Marshall" },
                new Pais {Id = 89, Descripcion = "Islas Salomón" },
                new Pais {Id = 90, Descripcion = "Israel" },
                new Pais {Id = 91, Descripcion = "Italia" },
                new Pais {Id = 92, Descripcion = "Jamaica" },
                new Pais {Id = 93, Descripcion = "Japón" },
                new Pais {Id = 94, Descripcion = "Jordania" },
                new Pais {Id = 95, Descripcion = "Kazajistán" },
                new Pais {Id = 96, Descripcion = "Kenia" },
                new Pais {Id = 97, Descripcion = "Kirguistán" },
                new Pais {Id = 98, Descripcion = "Kiribati" },
                new Pais {Id = 99, Descripcion = "Kuwait" },
                new Pais {Id = 100, Descripcion = "Laos" },
                new Pais {Id = 101, Descripcion = "Lesoto" },
                new Pais {Id = 102, Descripcion = "Letonia" },
                new Pais {Id = 103, Descripcion = "Líbano" },
                new Pais {Id = 104, Descripcion = "Liberia" },
                new Pais {Id = 105, Descripcion = "Libia" },
                new Pais {Id = 106, Descripcion = "Liechtenstein" },
                new Pais {Id = 107, Descripcion = "Lituania" },
                new Pais {Id = 108, Descripcion = "Luxemburgo" },
                new Pais {Id = 109, Descripcion = "Madagascar" },
                new Pais {Id = 110, Descripcion = "Malasia" },
                new Pais {Id = 111, Descripcion = "Malaui" },
                new Pais {Id = 112, Descripcion = "Maldivas" },
                new Pais {Id = 113, Descripcion = "Malí" },
                new Pais {Id = 114, Descripcion = "Malta" },
                new Pais {Id = 115, Descripcion = "Marruecos" },
                new Pais {Id = 116, Descripcion = "Mauricio" },
                new Pais {Id = 117, Descripcion = "Mauritania" },
                new Pais {Id = 118, Descripcion = "México" },
                new Pais {Id = 119, Descripcion = "Micronesia" },
                new Pais {Id = 120, Descripcion = "Moldavia" },
                new Pais {Id = 121, Descripcion = "Mónaco" },
                new Pais {Id = 122, Descripcion = "Mongolia" },
                new Pais {Id = 123, Descripcion = "Montenegro" },
                new Pais {Id = 124, Descripcion = "Mozambique" },
                new Pais {Id = 125, Descripcion = "Namibia" },
                new Pais {Id = 126, Descripcion = "Nauru" },
                new Pais {Id = 127, Descripcion = "Nepal" },
                new Pais {Id = 128, Descripcion = "Nicaragua" },
                new Pais {Id = 129, Descripcion = "Níger" },
                new Pais {Id = 130, Descripcion = "Nigeria" },
                new Pais {Id = 131, Descripcion = "Noruega" },
                new Pais {Id = 132, Descripcion = "Nueva Zelanda" },
                new Pais {Id = 133, Descripcion = "Omán" },
                new Pais {Id = 134, Descripcion = "Países Bajos" },
                new Pais {Id = 135, Descripcion = "Pakistán" },
                new Pais {Id = 136, Descripcion = "Palaos" },
                new Pais {Id = 137, Descripcion = "Panamá" },
                new Pais {Id = 138, Descripcion = "Papúa Nueva Guinea" },
                new Pais {Id = 139, Descripcion = "Paraguay" },
                new Pais {Id = 140, Descripcion = "Perú" },
                new Pais {Id = 141, Descripcion = "Polonia" },
                new Pais {Id = 142, Descripcion = "Portugal" },
                new Pais {Id = 143, Descripcion = "Reino Unido" },
                new Pais {Id = 144, Descripcion = "República Centroafricana" },
                new Pais {Id = 145, Descripcion = "República Checa" },
                new Pais {Id = 146, Descripcion = "República de Macedonia" },
                new Pais {Id = 147, Descripcion = "República del Congo" },
                new Pais {Id = 148, Descripcion = "República Democrática del Congo" },
                new Pais {Id = 149, Descripcion = "República Dominicana" },
                new Pais {Id = 150, Descripcion = "República Sudafricana" },
                new Pais {Id = 151, Descripcion = "Ruanda" },
                new Pais {Id = 152, Descripcion = "Rumanía" },
                new Pais {Id = 153, Descripcion = "Rusia" },
                new Pais {Id = 154, Descripcion = "Samoa" },
                new Pais {Id = 155, Descripcion = "San Cristóbal y Nieves" },
                new Pais {Id = 156, Descripcion = "San Marino" },
                new Pais {Id = 157, Descripcion = "San Vicente y las Granadinas" },
                new Pais {Id = 158, Descripcion = "Santa Lucía" },
                new Pais {Id = 159, Descripcion = "Santo Tomé y Príncipe" },
                new Pais {Id = 160, Descripcion = "Senegal" },
                new Pais {Id = 161, Descripcion = "Serbia" },
                new Pais {Id = 162, Descripcion = "Seychelles" },
                new Pais {Id = 163, Descripcion = "Sierra Leona" },
                new Pais {Id = 164, Descripcion = "Singapur" },
                new Pais {Id = 165, Descripcion = "Siria" },
                new Pais {Id = 166, Descripcion = "Somalia" },
                new Pais {Id = 167, Descripcion = "Sri Lanka" },
                new Pais {Id = 168, Descripcion = "Suazilandia" },
                new Pais {Id = 169, Descripcion = "Sudán" },
                new Pais {Id = 170, Descripcion = "Sudán del Sur" },
                new Pais {Id = 171, Descripcion = "Suecia" },
                new Pais {Id = 172, Descripcion = "Suiza" },
                new Pais {Id = 173, Descripcion = "Surinam" },
                new Pais {Id = 174, Descripcion = "Tailandia" },
                new Pais {Id = 175, Descripcion = "Tanzania" },
                new Pais {Id = 176, Descripcion = "Tayikistán" },
                new Pais {Id = 177, Descripcion = "Timor Oriental" },
                new Pais {Id = 178, Descripcion = "Togo" },
                new Pais {Id = 179, Descripcion = "Tonga" },
                new Pais {Id = 180, Descripcion = "Trinidad y Tobago" },
                new Pais {Id = 181, Descripcion = "Túnez" },
                new Pais {Id = 182, Descripcion = "Turkmenistán" },
                new Pais {Id = 183, Descripcion = "Turquía" },
                new Pais {Id = 184, Descripcion = "Tuvalu" },
                new Pais {Id = 185, Descripcion = "Ucrania" },
                new Pais {Id = 186, Descripcion = "Uganda" },
                new Pais {Id = 187, Descripcion = "Uruguay" },
                new Pais {Id = 188, Descripcion = "Uzbekistán" },
                new Pais {Id = 189, Descripcion = "Vanuatu" },
                new Pais {Id = 190, Descripcion = "Venezuela" },
                new Pais {Id = 191, Descripcion = "Vietnam" },
                new Pais {Id = 192, Descripcion = "Yemen" },
                new Pais {Id = 193, Descripcion = "Yibuti" },
                new Pais {Id = 194, Descripcion = "Zambia" },
                new Pais {Id = 195, Descripcion = "Zimbabue" }
            };

            return listaPaises;
        }
    }
}
